platform :ios, '9.1'
use_frameworks!

target 'FFSideMenu_Example', :exclusive => true do
  pod "FFSideMenu", :path => "../"
end

target 'FFSideMenu_Tests', :exclusive => true do
  pod "FFSideMenu", :path => "../"

  # pod 'FBSnapshotTestCase', :git => 'git@github.com:facebook/ios-snapshot-test-case.git', :branch => 'master'
end